version: '3'

services:
  functional_tests:
    container_name: functional_tests
    build: tests/functional/
    env_file:
      - environments/tests.env

  fastapi:
    container_name: fastapi
    restart: always
    build: .
    env_file:
      - environments/.env

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.0
    restart: always
    environment:
      discovery.type: single-node
#    ports:
#      - 9200:9200

  cache:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - cache:/data
#    ports:
#      - 6379:6379


volumes:
  cache: {}
  static: {}
  db: {}
  locale: {}
